This PR fixes build issue on s390x introduced with commit 394fb6267acba72ee984edcd331ad1bbde72056a: (#135)
vm_s390x.dasc:1807:60: error: 'SBuf' {aka 'struct SBuf'} has no member named 'p'

Signed-off-by: Artiom Vaskov <artiom.vaskov@ibm.com>